### ISSUE TITLE
Compilation Error Following Recent Modifications in CMakeLists.txt

### ISSUE THREAD

**Issue by thibaultfalque** [ptal/turbo#21]
**Description:**

After the changes introduced in [this commit](https://github.com/ptal/turbo/commit/526fefea59cb0a7c3dd6f04dedc4ce836a26a905), I encountered a compilation issue with the `turbo` project. The error occurs during the configuration step in CMake when using the preset "cpu-debug-local". It seems that the project is unable to recognize features for the CUDA compiler.

**Error Message:**
```plaintext
-- Configuring done (1.8s)
CMake Error in CMakeLists.txt:
  No known features for CUDA compiler

  ""

  version .
```

I have not the problem with the previous [CMakeLists](https://github.com/ptal/turbo/blob/1965fa8c5f55c48380dcd8d717c24d62f523a65b/CMakeLists.txt).

**Comment by ptal** [comment]
Should be fine now, it was because I forgot to push the changes to lala-parsing
